package nhlang

var PreferedLanguage string // language string
// eng esp cmn
var MyLangs = map[string]string{
	"eng-mn-intro-1":        "Encrypted Communications Using NATS ",
	"eng-mn-intro-2":        "for Additional Info.",
	"spa-mn-intro-1":        "Comunicaciones Encriptadas Usando NATS ",
	"spa-mn-intro-2":        "para Información Adicional.",
	"eng-mn-mt":             "Encryption",
	"spa-mn-mt":             "Cifrada",
	"eng-mn-err1":           "Missing panel: ",
	"spa-mn-err1":           "Falta el panel: ",
	"eng-mn-dark":           "Dark",
	"spa-mn-dark":           "Oscura",
	"eng-mn-light":          "Light",
	"spa-mn-light":          "Ligera",
	"eng-ps-title":          "Pass Reset",
	"spa-ps-title":          "Pasar Restablecer",
	"eng-ps-password":       "Enter Original Password",
	"spa-ps-passwordueue) ": "Ingrese la Contraseña Original",
	"eng-ps-passwordc1":     "Enter New Password",
	"spa-ps-passwordc1":     "Ingrese Nueva Clave",
	"eng-ps-passwordc2":     "Enter New Password Again",
	"spa-ps-passwordc2":     "Ingrese la Nueva Contraseña Nuevamente",
	"eng-ps-trypassword":    "Try Password",
	"spa-ps-trypassword":    "Probar Contraseña",
	"eng-ps-err1":           "Error Creating Password Hash ",
	"spa-ps-err1":           "Error al Crear Hash de Contraseña ",
	"eng-ps-err2":           "Error Creating Password Hash",
	"spa-ps-err2":           "Error al Crear Hash de Contraseña",
	"eng-ps-err3":           "Error Reading Password Hash",
	"spa-ps-err3":           "Error al Leer el Hash de la Contraseña",
	"eng-ps-err4":           "Error Passwords Do Not Match",
	"spa-ps-err4":           "Las Contraseñas de Error no Coinciden",
	"eng-ps-err5":           "Password Accepted",
	"spa-ps-err5":           "Contraseña Aceptada",
	"eng-ps-chgpassword":    "Change Password",
	"spa-ps-chgpassword":    "Cambiar la Contraseña",
	"eng-ps-err6":           "Error Pasword 1 Invalid",
	"spa-ps-err6":           "Error Contraseña 1 Inválida",
	"eng-ps-err7":           "Error Pasword Does Not Meet Requirements",
	"spa-ps-err7":           "La Contraseña de Error no Cumple con los Requisitos",
	"eng-ps-err8":           "Error Password 1 Does Not Match Password 2",
	"spa-ps-err8":           "Error La Contraseña 1 no Coincide con la Contraseña 2",
	"eng-ps-err9":           "Error Saving Password Hash",
	"spa-ps-err9":           "Error al Guardar el Hash de la Contraseña",
	"eng-ps-err10":          "Error Reading Password Hash",
	"spa-ps-err10":          "Error al Leer el Hash de la Contraseña",
	"eng-ps-err11":          "Error Invalid Password",
	"spa-ps-err11":          "Error Contraseña Inválida",
	"eng-ps-title1":         "Local File Encryption",
	"spa-ps-title1":         "Cifrado de Archivos Locales",
	"eng-ps-title2":         "Enter Password To Reset",
	"spa-ps-title2":         "Ingrese la Contraseña para Restablecer",
	"eng-ps-title3":         "Enter New Password",
	"spa-ps-title3":         "Ingrese Nueva Clave",
	"eng-ss-title":          "Settings",
	"spa-ss-title":          "Ajustes",
	"eng-ss-la":             "Prefered Language",
	"spa-ss-la":             "Idioma Preferido",
	"eng-ss-pl":             "Minimum Password Length",
	"spa-ss-pl":             "Longitud Mínima de la Contraseña",
	"eng-ss-ma":             "Message Max Age In Hours",
	"spa-ss-ma":             "Edad Máxima del Mensaje en Horas",
	"eng-ss-mcletter":       "Password Must Contain Letter",
	"spa-ss-mcletter":       "La Contraseña Debe Contener una Letra",
	"eng-ss-mcnumber":       "Password Must Contain Number",
	"spa-ss-mcnumber":       "La Contraseña Debe Contener un Número",
	"eng-ss-mcspecial":      "Password Must Contain Special",
	"spa-ss-mcspeciaueue":   "Change Settings",
	"spa-ss-heading":        "Cambiar Ajustes",
	"eng-cs-title":          "Certificates",
	"spa-cs-title":          "Certificados",
	"eng-cs-ca":             "CAROOT Certificate",
	"spa-cs-ca":             "Certificado CAROOT",
	"eng-cs-cc":             "CLIENT Certificate",
	"spa-cs-cc":             "Certificado CLIENTE",
	"eng-cs-ck":             "CLIENT Key",
	"spa-cs-ck":             "Clave CLIENTE",
	"eng-cs-ss":             "Save Certificates",
	"spa-cs-ss":             "Guardar Certificados",
	"eng-cs-err1":           "Error CAROOT is Invalid",
	"spa-cs-err1":           "Error CAROOT no es Válido",
	"eng-cs-err2":           "Error CLIENT CERTIFICATE is invalid ",
	"spa-cs-err2":           "Error CERTIFICADO DE CLIENTE no es Válido",
	"eng-cs-err3":           "Error CLIENT KEY is Invalid",
	"spa-cs-err3":           "Error CLAVE DE CLIENTE no es Cálida",
	"eng-cs-heading":        "Certificate Management",
	"spa-cs-heading":        "Gestión de Certificados",
	"eng-cs-lf":             "Logon First",
	"spa-cs-lf":             "Iniciar Sesión Primero",
	"eng-ls-title":          "Logon",
	"spa-ls-title":          "Iniciar sesión",
	"eng-ls-password":       "Password For Local Encryption",
	"spa-ls-password":       "Contraseña para el Cifrado Local",
	"eng-ls-alias":          "Alias",
	"spa-ls-alias":          "Alias",
	"eng-ls-queue":          "Queue",
	"spa-ls-queue":          "Cola",
	"eng-ls-queuepass":      "Queue Password",
	"spa-ls-queuepass":      "Contraseña de Cola",
	"eng-ls-trypass":        "Try Password",
	"spa-ls-trypass":        "Probar Contraseña",
	"eng-ls-err1":           "logon.go Error Creating Password Hash 24",
	"spa-ls-err1":           "logon.go Error al Crear el Hash de la Contraseña 24",
	"eng-ls-err2":           "logon.go Error Loading Password Hash 24",
	"spa-ls-err2":           "logon.go Error al Cargar el Hash de la Contraseña 24",
	"eng-ls-err3":           "logon.go Error Invalid Password",
	"spa-ls-err3":           "logon.go Error Contraseña no Válida",
	"eng-ls-err4":           "logon.go Error URL Incorrect Format",
	"spa-ls-err4":           "logon.go URL de Error Formato Incorrecto",
	"eng-ls-err5":           "Error Invalid Queue Password 24",
	"spa-ls-err5":           "Error Contraseña de Cola no Válida 24",
	"eng-ls-err6-1":         "Error Queue Password Length is ",
	"spa-ls-err6-1":         "La Longitud de la Contraseña de la Cola de Errores es ",
	"eng-ls-err6-2":         " should be length of 24",
	"spa-ls-err6-2":         " Debe Tener una Longitud de 24",
	"eng-ls-err7":           "No NATS connection",
	"spa-ls-err7":           "Sin Conexión NATS",
	"eng-ls-erase":          "Security Erase",
	"spa-ls-erase":          "Borrado de seguridad",
	"eng-ls-clogon":         "Communications Logon",
	"spa-ls-clogon":         "Inicio de Sesión de Comunicaciones",
	"eng-ls-err8":           "No JETSTREAM Connection",
	"spa-ls-err8":           "Sin Conexión JETSTREAM ",
	"eng-ms-title":          "Messages",
	"spa-ms-title":          "Mensajes",
	"eng-ms-mm":             "Enter Message For Encryption",
	"spa-ms-mm":             "Ingrese el Mensaje Para el Cifrado",
	"eng-ms-header1":        "Select An Item From The List",
	"spa-ms-header1":        "Seleccione un Elemento de la Lista",
	"eng-ms-err1":           "NATS No Connection",
	"spa-ms-err1":           "NATS sin Conexión",
	"eng-ms-sm":             "Send Message",
	"spa-ms-sm":             "Enviar Mensaje",
	"eng-ms-header2":        "NATS Messaging",
	"spa-ms-header2":        "Mensajería NATS",
	"eng-ms-cpy":            "Copy To Clipboard",
	"spa-ms-cpy":            "Copiar al Portapapeles",
	"eng-ms-err2":           "NATS No Connection",
	"spa-ms-err2":           "NATS sin Conexión",
	"eng-ms-err3":           "Could Not Add Consumer",
	"spa-ms-err3":           "No se Pudo Agregar el Consumidor",
	"eng-ms-err4":           "Error Pull Subscribe ",
	"spa-ms-err4":           "Error Extraer Suscribirse ",
	"eng-ms-err5":           "Error Fetch ",
	"spa-ms-err5":           "Recuperación de Errores ",
	"eng-ms-err6-1":         "Recieved ",
	"spa-ms-err6-1":         "Recibida ",
	"eng-ms-err6-2":         " Messages ",
	"spa-ms-err6-2":         " Mensajes ",
	"eng-ms-err6-3":         " Logs",
	"spa-ms-err6-3":         " Registros",
	"eng-ms-err7":           "Please Logon First",
	"spa-ms-err7":           "Por Favor Ingresa Primero",
	"eng-es-title":          "Enc/Dec",
	"spa-es-title":          "Codificar/Descodificar",
	"eng-es-pw":             "Enc/Dec",
	"spa-es-pw":             "Codificar/Descodificar",
	"eng-es-pass":           "Enter Password to Use For Encryption 24",
	"spa-es-pass":           "Ingrese la contraseña para usar para el cifrado 24",
	"eng-es-mv":             "Enter Value",
	"spa-es-mv":             "Introducir Valor",
	"eng-es-mo":             "Output Shows Up Here",
	"spa-es-mo":             "La Salida Aparece Aquí",
	"eng-es-em":             "Encrypt Message",
	"spa-es-em":             "Cifrar Mensaje",
	"eng-esT-err1":          "Error Invalid Password",
	"spa-es-err1":           "Error Contraseña Inválida",
	"eng-es-err2-1":         "Error Password Length is ",
	"spa-es-err2-1":         "La Longitud de la Contraseña de Error es ",
	"eng-es-err2-2":         " Should be Length of 24",
	"spa-es-err2-2":         " Debe Tener una Longitud de 24",
	"eng-es-err3":           "Error Input Text",
	"spa-es-err3":           "Texto de Entrada de Error",
	"eng-es-err4":           "Cannot Encrypt Input Text",
	"spa-es-err4":           "No se Puede Cifrar el Texto de Entrada",
	"eng-es-err5":           "Cannot Decrypt Input Text",
	"spa-es-err5":           "No se Puede Descifrar el Texto de Entrada",
	"eng-es-head1":          "Input",
	"spa-es-head1":          "Aporte",
	"eng-es-head2":          "Output",
	"spa-es-head2":          "Producción",
	"eng-log-nc":            "Path to nats Configuration File \nFor TLS Certificate Paths",
	"eng-hash-err1":         "Hash Error on Write",
	"spa-hash-err1":         "Error de Hash al Escribir ",
	"eng-hash-err2":         "Error Creating Password Hash 24",
	"spa-hash-err2":         "Error al Crear el Hash de la Contraseña 24",
	"eng-hash-err3":         "Hash Error on Read ",
	"spa-hash-err3":         "Error de Hash en Lectura ",
	"eng-lang-err1":         "Language Error not Found ",
	"spa-lang-err1":         "Error de Idioma no Encontrado ",
}

func GetLangs(tr string) string {

	value, err := MyLangs[PreferedLanguage+"-"+tr]
	//log.Println("GetLangs ", PreferedLanguage+"-"+mystring)
	if err == false {
		return GetLangs("lang-err1") + " " + tr
	}
	return value
}
