Website = "https://newhorizons3000.org"

[Details]
  Icon = "logo.png"
<<<<<<< HEAD
  Name = "NH3000"
  ID = "org.nh3000.nh3000"
  Version = "1.0.0"
  Build = 39
=======
  Name = "nh3000"
  ID = "org.nh3000.nh3000"
  Version = "1.0.0"
  Build = 41
>>>>>>> 99fb7ce (V0.9)
